# This is the list of (privileged) users,
#  whose credentials are managed through Ansible.
#
# Groups, under `user_groups`, are lists of usernames.
# Each username *MUST* occur under `users`,
#  with the following attributes:
#  - key: either a plain SSH key or a URL to a SSH key file
#         If not set, the key *MUST* be in `files/keys/$user.pub`
#  - irc: the user's nick on IRC, if different from the username
#  - github: the username on Github, if different
#  - unix: the username in LDAP, if different
#  - irc_oper: an object with a type attribute (usually "sha1")
#              and a pass attribute (usually the crypt(3)-format password).
#  - mail: the user's email address; defaults to username@hashbang.sh


user_groups:
  admins:
    - alissa
    - cbrooks
    - daurnimator
    - dgrove
    - kellerfuchs
    - lrvick
    - viaken

  # admins are implicitely irc_ops
  irc_ops:
    - aagat
    - SaidinWoT
    - stinethebean
    - Xomen

users:
  # Admins
  alissa:
    github: ChickenNuggers
    irc_oper:
      type: sha1
      pass: "{{ vault_users.alissa.irc_operpass }}"
    mail: "{{ vault_users.alissa.mail }}"

  cbrooks:
    github: connerbrooks
    irc_oper:
      type: sha1
      pass: "{{ vault_users.cbrooks.irc_operpass }}"
    mail: "{{ vault_users.cbrooks.mail }}"

  daurnimator:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.daurnimator.irc_operpass }}"
    mail: "{{ vault_users.daurnimator.mail }}"

  dgrove:
    key: https://github.com/drGrove.keys
    github: drGrove
    irc_oper:
      type: sha1
      pass: "{{ vault_users.dgrove.irc_operpass }}"
    mail: "{{ vault_users.dgrove.mail }}"

  kellerfuchs:
    irc_oper:
      type: sslclientcertfp
      pass: "0A:D8:51:3B:C6:1A:AB:6C:78:17:56:14:0A:D9:5E:43:4A:D9:33:64:04:5D:7F:4D:45:57:C2:86:33:D5:62:5B"

  lrvick:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.lrvick.irc_operpass }}"
    mail: "{{ vault_users.lrvick.mail }}"

  viaken:
    github: dpflug
    irc_oper:
      type: sha1
      pass: "{{ vault_users.viaken.irc_operpass }}"
    mail: "{{ vault_users.viaken.mail }}"


  # IRC ops
  aagat:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.aagat.irc_operpass }}"

  SaidinWoT:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.SaidinWoT.irc_operpass }}"

  stinethebean:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.stinethebean.irc_operpass }}"

  Xomen:
    irc_oper:
      type: sha1
      pass: "{{ vault_users.Xomen.irc_operpass }}"
